version: 2.1
jobs:
    hello-world:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - run:
                  name: hello world
                  command: |
                      echo 'aaaa test hello world'
    i-have-code:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - run:
                  name: hello world 2
                  command: |
                      echo 'aaaa test hello world'
workflows:
    version: 2
    myflows:
        jobs:
            - hello-world
            - i-have-code:
                  type: approval
                  requires:
                      - hello-world
