version: 2.1
jobs:
    hello-world:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - run:
                  name: hello world
                  command: |
                      echo 'aaaa test hello world'
    i-have-code:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - run:
                  name: hello world 2
                  command: |
                      echo 'aaaa test hello world'
    i-have-code2:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - run:
                  name: hello world 3
                  command: |
                      echo 'aaaa test hello world3333'

workflows:
    version: 2
    myflows:
        jobs:
            - hello-world
            - i-have-code:
                  requires:
                      - hello-world
            - i-have-code2
            - deploy:
                  type: approval
                  requires:
                      - i-have-code
                      - i-have-code2
